Repository serokell/o-clock, pull requests merged in 2018-02, with the labels that each got.

#86 [#81] Rename TimeStamp to Timestamp
  .gitignore
  CHANGELOG.md
  o-clock.cabal
  src/Time.hs
  src/Time/Formatting.hs
  src/Time/Timestamp.hs
  test/Spec.hs
  test/Test/Time/Timestamp.hs
Labels: refactoring

#87 [#63] Add SeriesP class
  CHANGELOG.md
  o-clock.cabal
  src/Time.hs
  src/Time/Series.hs
Labels: api & interface

#88 [#64] Add property tests for unitsP . unitsF = id
  CHANGELOG.md
  test/Test/Time/Property.hs
Labels: tests

#89 [#71] Add toNum function
  CHANGELOG.md
  src/Time/Units.hs
Labels: api & interface

#90 [#85] Add fromUnixTime function
  CHANGELOG.md
  src/Time/Timestamp.hs
Labels: api & interface

#92 Refine the type of 'ratDiff'
  src/Time/Timestamp.hs
Labels: api & interface, refactoring

#96 [#95] Add Semigroup and Monoid instances for Time
  .gitignore
  CHANGELOG.md
  o-clock.cabal
  src/Time/Units.hs
Labels: api & interface

#97 [#93] Remove transformers dependency
  CHANGELOG.md
  o-clock.cabal
Labels: refactoring
